# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sample_start_info <- function(m1, m2, m3, m4, w = as.numeric( c(0.33,0.33,0.33))) {
    .Call('sequencesAnonymizer_sample_start_info', PACKAGE = 'sequencesAnonymizer', m1, m2, m3, m4, w)
}

sample_starting_state <- function(m1, m2, m3, m4, w = as.numeric( c(0.33,0.33,0.33))) {
    .Call('sequencesAnonymizer_sample_starting_state', PACKAGE = 'sequencesAnonymizer', m1, m2, m3, m4, w)
}

sample_transition <- function(m1, m2, m3, m4, w = as.numeric( c(0.33,0.33,0.33))) {
    .Call('sequencesAnonymizer_sample_transition', PACKAGE = 'sequencesAnonymizer', m1, m2, m3, m4, w)
}

